import Head from 'next/head';
import { Header } from '@components/Header';
import { Main } from '@components/Main';
import { Footer } from '@components/Footer';


export default function Home() {
  return (
    <>
      <Head>
        <title>mercadolibre</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Header />
      <Main />
      <Footer />


    </>
  )
}
